---
- name: restart adguard_exporter
  systemd:
    daemon_reload: true
    name: adguard_exporter
    state: restarted
  become: true
  tags: adguard_exporter

- name: reload adguard_exporter
  systemd:
    name: adguard_exporter
    state: reloaded
  become: true
  tags: adguard_exporter